charts/docreader/Chart.yaml, charts/docreader/templates/hpa.yaml, charts/faceapi/templates/ingress.yaml
Adopt HPA to 1.22+ versions; force ingress to support kubernetes 1.19>=
=> docreader. HPA/Ingress improvements

charts/faceapi/README.md, charts/faceapi/values.yaml
https://app.clickup.com/t/4535044/SP-13181
=> Proofread: Minor edits

charts/api-gateway/Chart.yaml, charts/api-gateway/templates/configmaps/env_settings.tpl, charts/api-gateway/values.yaml
added airflowUser and airflowPassword
=> Variables change

charts/faceapi/Chart.yaml, charts/faceapi/templates/config.tpl, charts/faceapi/values.yaml
Added:
- `config.service.detectMatch.audit`
- `config.service.webServer.logging.access.format`
- `config.service.database.passwordlessAuth`
=> faceapi. config update. 

charts/faceapi/Chart.yaml, charts/faceapi/templates/config.tpl, charts/faceapi/values.yaml
Add
- `config.service.detectMatch.selfOrigins`
- `config.service.liveness.consistency`
- `config.service.liveness.config.recalculateLandmarks`
Minor fixes
=> faceapi. update config

charts/docreader/Chart.yaml, charts/docreader/README.md, charts/docreader/templates/config.tpl, charts/docreader/values.yaml, charts/faceapi/Chart.yaml, charts/faceapi/README.md
Docreader. Add `config.service.webServer.logging.access.format`
=> docreader. Add custom log format 

.github/workflows/chart-version.yaml, charts/docreader/Chart.yaml, charts/docreader/templates/deployment.yaml, charts/faceapi/Chart.yaml, charts/faceapi/templates/deployment.yaml
https://app.clickup.com/t/4535044/SP-17987
Fix for probes/services custom port.
=> Fix for probes/services custom port

charts/docreader/Chart.yaml, charts/docreader/README.md, charts/docreader/templates/deployment.yaml, charts/docreader/values.yaml, charts/faceapi/Chart.yaml, charts/faceapi/templates/deployment.yaml
Migrate probes:
- liveness /api/ping ➝ /api/healthz
- readiness /api/readiness ➝ /api/readyz
- startup /api/readiness ➝ /api/readyz
https://app.clickup.com/t/4535044/SP-18111
=> Migrate liveness/readiness/startup probes to healthz/readyz

charts/docreader/Chart.yaml, charts/docreader/README.md, charts/docreader/templates/_helpers.tpl, charts/docreader/templates/config.tpl, charts/docreader/templates/deployment.yaml, charts/docreader/templates/sdk-error-pvc.yaml, charts/docreader/values.yaml
Add SDK Error Log support for `Docreader` Helm chart
https://app.clickup.com/t/4535044/SP-20467
- rendered manually with different values
- deployed to local Kubernetes cluster
=> [Docreader] Add support for SDK Error Log

charts/faceapi/Chart.yaml, charts/faceapi/templates/config.tpl, charts/faceapi/values.yaml
Add the ability to change some SDK parameters.
https://app.clickup.com/t/4535044/SP-20514
- rendered manually with different values
=> Add SDK parameters

charts/docreader/Chart.yaml, charts/docreader/templates/_helpers.tpl, charts/faceapi/Chart.yaml, charts/faceapi/templates/_helpers.tpl
Fix labels propagation to underlying resources.
=> Fix labels propagation

charts/docreader/Chart.yaml, charts/docreader/README.md, charts/docreader/templates/config.tpl, charts/docreader/values.yaml, charts/faceapi/Chart.yaml, charts/faceapi/README.md, charts/faceapi/templates/config.tpl, charts/faceapi/values.yaml
https://app.clickup.com/t/4535044/SP-20977
storage. az. Add option to specify storageAccount for Azure identity case
=> docreader/faceapi. storage. az

charts/docreader/Chart.yaml, charts/docreader/README.md, charts/docreader/templates/config.tpl, charts/docreader/values.yaml
Add support for Housekeeper configuration
=> Add housekeeper support for docreader

.github/workflows/release-charts.yml
Add OpenSearch Helm chart repo to fix Releaser workflow.
=> Fix releaser workflow

charts/idv/Chart.yaml, charts/idv/templates/config.tpl, charts/idv/values.yaml
Add CORS support for IDV Helm chart
=> Add CORS support for IDV

charts/idv/Chart.lock, charts/idv/Chart.yaml, charts/idv/templates/NOTES.txt, charts/idv/templates/_helpers.tpl, charts/idv/templates/config.tpl, charts/idv/values.yaml
Fix prometheus-statsd-exporter subchart via alias to mitigate dashes in name
https://app.clickup.com/t/4535044/SP-24444
=> helm. idv. Fix prometheus-statsd-exporter subchart

charts/idv/Chart.lock, charts/idv/Chart.yaml, charts/idv/templates/NOTES.txt, charts/idv/templates/_helpers.tpl, charts/idv/templates/config.tpl, charts/idv/values.yaml
https://app.clickup.com/t/4535044/SP-24444
=> helm. idv. Change alias to statsd

charts/idv/Chart.yaml, charts/idv/values.yaml
fix statsd default rendered config
=> helm. idv. statsd mapping config minor fix

charts/idv/Chart.yaml, charts/idv/templates/config.tpl, charts/idv/values.yaml
- Enable MongoDB Atlas support for IDV config
- Small fix for default CORS config values
=> Add atlas db support in config, fix cors config

charts/idv/Chart.yaml, charts/idv/templates/config.tpl, charts/idv/values.yaml
Add assets support for IDV Helm chart in storage section
=> Add assets support

charts/idv/Chart.yaml, charts/idv/values.yaml
Set workers number to auto
https://app.clickup.com/t/4535044/SP-24709
https://github.com/regulaforensics/idv-aws-deployment/pull/32
=> Set workers number to auto

charts/idv/Chart.yaml, charts/idv/templates/_helpers.tpl, charts/idv/templates/config.tpl, charts/idv/templates/deployment-indexer.yaml, charts/idv/values.yaml
Add new service - Indexer.
Add cronWorkflow job for Scheduler.
https://app.clickup.com/t/4535044/SP-25118
=> New service (indexer)
